package synclayer

import (
	"context"
	"errors"
	"net/http"
	"strconv"
)

// ---------------------------------------------------------------------------
// Network options, ALG and UPnP (the web UI's Advanced > Network and UPnP
// pages) plus the firewall settings that share the Network page.
// ---------------------------------------------------------------------------

// RemoteAccess is the remote (or secure) management block of NetworkOption.
//
// The device keeps a single port for both blocks: verified on VER-01.06.05-EA
// that writing remoteAccess.port changes the port secureAccess reports as well,
// so only one of them can be owned by a caller.
type RemoteAccess struct {
	Active bool `json:"active"`
	Port   int  `json:"port"`
}

// NetworkOption mirrors GET /api/v1/service/networkOption.
type NetworkOption struct {
	IPSecPassthrough bool         `json:"ipsecPassthrough"`
	PPTPPassthrough  bool         `json:"pptpPassthrough"`
	L2TPPassthrough  bool         `json:"l2tpPassthrough"`
	WANBlocking      bool         `json:"wanBlocking"`
	ICMPv6Blocking   bool         `json:"icmpv6Blocking"`
	NATTCPTimer      int          `json:"natTcpTimer"`
	NATUDPTimer      int          `json:"natUdpTimer"`
	RemoteAccess     RemoteAccess `json:"remoteAccess"`
	SecureAccess     RemoteAccess `json:"secureAccess"`
	Multicast        bool         `json:"multicast"`
}

// GetNetworkOption returns the device-wide network options.
func (c *Client) GetNetworkOption(ctx context.Context) (*NetworkOption, error) {
	var opts NetworkOption
	if err := c.request(ctx, http.MethodGet, "/service/networkOption", nil, &opts); err != nil {
		return nil, err
	}
	return &opts, nil
}

// UpdateNetworkOption writes the device-wide network options.
//
// The whole object is replaced, so callers must replay a value they just read
// for every field they do not mean to change (verified on VER-01.06.05-EA).
func (c *Client) UpdateNetworkOption(ctx context.Context, opts NetworkOption) error {
	return c.request(ctx, http.MethodPut, "/service/networkOption", opts, nil)
}

// ALGEntry is one application-layer gateway helper.
type ALGEntry struct {
	ID          int    `json:"id,omitempty"`
	DisplayName string `json:"displayName,omitempty"`
	ServiceCode string `json:"serviceCode"`
	Active      bool   `json:"active"`
}

// ListALG returns the ALG helpers the device supports.
func (c *Client) ListALG(ctx context.Context) ([]ALGEntry, error) {
	var entries []ALGEntry
	if err := c.request(ctx, http.MethodGet, "/service/alg", nil, &entries); err != nil {
		return nil, err
	}
	return entries, nil
}

// UpdateALG writes the ALG helpers.
//
// Verified on VER-01.06.05-EA: the write replaces the whole list, and an entry
// that is left out is switched off rather than kept, so callers must replay
// every entry they do not mean to disable.
func (c *Client) UpdateALG(ctx context.Context, entries []ALGEntry) error {
	return c.request(ctx, http.MethodPut, "/service/alg", entries, nil)
}

// UPnP mirrors GET /api/v1/service/upnp.
type UPnP struct {
	Active   bool `json:"active"`
	Interval int  `json:"interval"`
	TTL      int  `json:"ttl"`
}

// GetUPnP returns the UPnP configuration. The device-wide port mapping list is
// generated by clients and is not part of it.
func (c *Client) GetUPnP(ctx context.Context) (*UPnP, error) {
	var upnp UPnP
	if err := c.request(ctx, http.MethodGet, "/service/upnp", nil, &upnp); err != nil {
		return nil, err
	}
	return &upnp, nil
}

// UpdateUPnP writes the UPnP configuration.
//
// Verified on VER-01.06.05-EA: all three fields are required (a write carrying
// only active is refused), and switching UPnP off keeps the interval and TTL.
func (c *Client) UpdateUPnP(ctx context.Context, upnp UPnP) error {
	return c.request(ctx, http.MethodPut, "/service/upnp", upnp, nil)
}

// FirewallBlocks is the IPv4 block-flag set of the firewall.
type FirewallBlocks struct {
	FragmentedIPPackets bool `json:"fragmentedIpPackets"`
	PortScanDetection   bool `json:"portScanDetection"`
	IPFlood             bool `json:"ipFlood"`
	IPSpoofing          bool `json:"ipSpoofing"`
}

// FirewallIPv4 is the IPv4 half of the firewall settings. Level selects one of
// the device's rule banks (its rules are read-only).
type FirewallIPv4 struct {
	Active bool           `json:"active"`
	Level  string         `json:"level"`
	Blocks FirewallBlocks `json:"blocks"`
}

// FirewallIPv6 is the IPv6 half of the firewall settings.
type FirewallIPv6 struct {
	Active bool `json:"active"`
}

// Firewall mirrors GET /api/v1/security/firewall.
//
// The aggregate document and the per-family endpoints (/security/firewall/ipv4
// and /ipv6) are views of the same state: verified on VER-01.06.05-EA that a
// change made through either is reported by the other.
type Firewall struct {
	IPv4 FirewallIPv4 `json:"ipv4"`
	IPv6 FirewallIPv6 `json:"ipv6"`
}

// GetFirewall returns the firewall settings.
func (c *Client) GetFirewall(ctx context.Context) (*Firewall, error) {
	var fw Firewall
	if err := c.request(ctx, http.MethodGet, "/security/firewall", nil, &fw); err != nil {
		return nil, err
	}
	return &fw, nil
}

// UpdateFirewall writes the firewall settings through the aggregate endpoint.
func (c *Client) UpdateFirewall(ctx context.Context, fw Firewall) error {
	return c.request(ctx, http.MethodPut, "/security/firewall", fw, nil)
}

// ---------------------------------------------------------------------------
// IPv6 static routes
// ---------------------------------------------------------------------------

// StaticRouteIPv6 mirrors one entry of GET /api/v1/service/staticRouteIpv6.
//
// The IPv6 table takes a prefix length where the IPv4 table takes a netmask.
// Verified on VER-01.06.05-EA: a write carrying a "subnet" field instead stores
// prefixLength 0, so the prefix length is the field that matters.
type StaticRouteIPv6 struct {
	ID            int    `json:"id,omitempty"`
	Active        bool   `json:"active"`
	Status        string `json:"status,omitempty"`
	DestinationIP string `json:"destinationIP"`
	PrefixLength  int    `json:"prefixLength"`
	Gateway       string `json:"gateway"`
	Interface     int    `json:"interface"`
	IfName        string `json:"ifName,omitempty"`
}

type staticRouteIPv6List struct {
	Active                bool              `json:"active"`
	List                  []StaticRouteIPv6 `json:"list"`
	AvailableWanInterface []WanInterface    `json:"availableWanInterface"`
	MaxRules              int               `json:"maxRules"`
}

// ListStaticRoutesIPv6 returns every configured IPv6 static route.
func (c *Client) ListStaticRoutesIPv6(ctx context.Context) ([]StaticRouteIPv6, error) {
	var resp staticRouteIPv6List
	if err := c.request(ctx, http.MethodGet, "/service/staticRouteIpv6", nil, &resp); err != nil {
		return nil, err
	}
	return resp.List, nil
}

// GetStaticRouteIPv6 returns a single route by id.
func (c *Client) GetStaticRouteIPv6(ctx context.Context, id int) (*StaticRouteIPv6, error) {
	routes, err := c.ListStaticRoutesIPv6(ctx)
	if err != nil {
		return nil, err
	}
	for i := range routes {
		if routes[i].ID == id {
			return &routes[i], nil
		}
	}
	return nil, nil
}

// CreateStaticRouteIPv6 adds a route and returns its device-assigned id.
func (c *Client) CreateStaticRouteIPv6(ctx context.Context, route StaticRouteIPv6) (int, error) {
	var resp struct {
		ID int `json:"id"`
	}
	if err := c.request(ctx, http.MethodPost, "/service/staticRouteIpv6", route, &resp); err != nil {
		return 0, err
	}
	if resp.ID != 0 {
		return resp.ID, nil
	}
	return c.findStaticRouteIPv6ID(ctx, route)
}

// UpdateStaticRouteIPv6 replaces an existing route and returns the route's id
// afterwards. As on the IPv4 table the firmware implements an update as a
// delete followed by a create (verified on VER-01.06.05-EA: the id changed on
// every update), so the id is not stable and is resolved again.
func (c *Client) UpdateStaticRouteIPv6(ctx context.Context, id int, route StaticRouteIPv6) (int, error) {
	route.ID = id
	if err := c.request(ctx, http.MethodPut, "/service/staticRouteIpv6/"+strconv.Itoa(id), route, nil); err != nil {
		return 0, err
	}
	return c.findStaticRouteIPv6ID(ctx, route)
}

// findStaticRouteIPv6ID locates a route by its full identity. The interface
// name is only compared for WAN routes because the firmware reports "br0" for
// LAN routes.
func (c *Client) findStaticRouteIPv6ID(ctx context.Context, route StaticRouteIPv6) (int, error) {
	routes, err := c.ListStaticRoutesIPv6(ctx)
	if err != nil {
		return 0, err
	}
	matches := make([]int, 0, 1)
	for i := range routes {
		if routes[i].DestinationIP != route.DestinationIP ||
			routes[i].PrefixLength != route.PrefixLength ||
			routes[i].Gateway != route.Gateway ||
			routes[i].Interface != route.Interface {
			continue
		}
		if route.Interface != 0 && routes[i].IfName != route.IfName {
			continue
		}
		matches = append(matches, routes[i].ID)
	}
	if len(matches) == 1 {
		return matches[0], nil
	}
	return 0, errors.New("route could not be uniquely identified after the operation")
}

// DeleteStaticRouteIPv6 removes a route.
func (c *Client) DeleteStaticRouteIPv6(ctx context.Context, id int) error {
	return c.request(ctx, http.MethodDelete, "/service/staticRouteIpv6/"+strconv.Itoa(id), nil, nil)
}

// SetStaticRoutesIPv6Active turns the IPv6 routing table on or off.
func (c *Client) SetStaticRoutesIPv6Active(ctx context.Context, active bool) error {
	return c.request(ctx, http.MethodPost, "/service/staticRouteIpv6/active", map[string]any{"active": active}, nil)
}
